---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-wind1-wind-turbine-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/stefan-bergstein/rhdh-wind1-wind-turbine-gitops
